version: '3.8'

services:
  app:
    build: .
    ports:
      - '6669:6669'
    environment:
      TZ: Asia/Tokyo
      PORT: 6669
    volumes:
      - type: bind
        source: ./config.json
        target: /app/config.json
    init: true
